param([string]$ProjectRoot = (Split-Path -Parent $PSScriptRoot))
$ErrorActionPreference = 'Stop'
try {
    $localText = [IO.File]::ReadAllText((Join-Path $ProjectRoot 'Core\Inc\Datos_editar.h'))
    $profileText = [IO.File]::ReadAllText((Join-Path $ProjectRoot 'Core\Inc\tqt_identity.h'))
    function Read-Define([string]$Text,[string]$Name) {
        $matchesFound = [regex]::Matches($Text, ('(?m)^\s*#define\s+' + $Name + '\s+"([^"\r\n]+)"\s*(?:/\*.*\*/)?\s*$'))
        if ($matchesFound.Count -ne 1) { throw "Definicion invalida o repetida: $Name" }
        return $matchesFound[0].Groups[1].Value
    }
    $boardName = Read-Define $localText 'TQT_LOCAL_NAME'
    $boardId = Read-Define $localText 'TQT_LOCAL_ID'
    $boardMac = (Read-Define $localText 'TQT_LOCAL_MAC_R').ToUpperInvariant()
    $boardHw = Read-Define $localText 'TQT_LOCAL_HW'
    $firmwareVersion = Read-Define $localText 'TQT_FW_VERSION'
    $compatibleHw = Read-Define $profileText 'TQT_HW_COMPATIBLE'
    $mcu = Read-Define $profileText 'TQT_MCU_NAME'
    if ($mcu -cne 'STM32F103RET6') { throw 'Perfil MCU no soportado' }
    if ($boardId -cnotmatch '^[0-9]{4}$') { throw 'ID de R2 debe contener cuatro digitos' }
    if ($boardHw -cnotmatch '^[0-9]+(?:\.[0-9]+)*$' -or $boardHw.Length -gt 7) { throw 'HW invalido' }
    if ($firmwareVersion -cnotmatch '^[0-9]+(?:\.[0-9]+)*$' -or $firmwareVersion.Length -gt 7) { throw 'FW invalido' }
    if ($boardHw -cne $compatibleHw) { throw 'HW no compatible con este firmware' }
    $r1Pattern = '^' + [regex]::Escape('TQT_R1_V' + $boardHw.Replace('.','') + '_') + '[0-9]{4}$'
    if ($boardName -cnotmatch $r1Pattern -or $boardName.Length -gt 22) { throw 'Nombre de R1 invalido: comprobar HW y cuatro digitos de R1' }
    if ($boardMac -cnotmatch '^(?:[0-9A-F]{2}:){5}[0-9A-F]{2}$' -or $boardMac -in @('00:00:00:00:00:00','FF:FF:FF:FF:FF:FF')) { throw 'MAC de R2 invalida' }
    $payload = New-Object 'System.Collections.Generic.List[byte]'
    $payload.AddRange([BitConverter]::GetBytes([uint32]0x31545154))
    $payload.AddRange([BitConverter]::GetBytes([uint16]2))
    $payload.AddRange([BitConverter]::GetBytes([uint16]76))
    function Add-Field([string]$Value,[int]$Length) {
        if ($Value -cmatch '[^\x20-\x7E]' -or $Value.Length -ge $Length) { throw 'Campo no ASCII o demasiado largo' }
        $bytes = New-Object byte[] $Length
        [Text.Encoding]::ASCII.GetBytes($Value).CopyTo($bytes,0)
        $payload.AddRange($bytes)
    }
    Add-Field $boardName 23
    Add-Field $boardId 5
    Add-Field $boardMac 18
    Add-Field $boardHw 8
    Add-Field $firmwareVersion 8
    $payload.AddRange([byte[]]@(0,0))
    [uint32]$crc = [uint32]::MaxValue
    foreach ($byte in $payload) {
        $crc = $crc -bxor [uint32]$byte
        for ($bit=0; $bit -lt 8; $bit++) {
            if (($crc -band 1) -eq 1) { $crc = ($crc -shr 1) -bxor [uint32]3988292384 }
            else { $crc = $crc -shr 1 }
        }
    }
    $crc = $crc -bxor [uint32]::MaxValue
    $payload.AddRange([BitConverter]::GetBytes([uint32]$crc))
    if ($payload.Count -ne 76) { throw 'Tamano de identidad incorrecto' }
    $literal = ($payload | ForEach-Object { '0x{0:X2}' -f $_ }) -join ', '
    $content = @"
/* GENERATED by tools/generate_identity.ps1. Edit Datos_editar.h instead.
 * CRC32 ISO-HDLC over bytes 0..71; FW $firmwareVersion / HW $boardHw / schema 2. */
__attribute__((used, aligned(4), section(".tqt_identity")))
const uint8_t tqt_identity_template[76] = { $literal };
"@
    $destination = Join-Path $ProjectRoot 'Core\Inc\tqt_identity_generated.h'
    if (-not (Test-Path -LiteralPath $destination) -or [IO.File]::ReadAllText($destination) -cne $content) {
        [IO.File]::WriteAllText($destination,$content,[Text.Encoding]::ASCII)
    }
    Write-Output "Identidad generada: $boardName | R2 ID $boardId | R2 MAC $boardMac | HW $boardHw | FW $firmwareVersion | CRC32 $('{0:X8}' -f $crc)"
} catch { Write-Error $_; exit 1 }
